# Code Snippets

import http.client

conn = http.client.HTTPSConnection("unogs-unogs-v1.p.rapidapi.com")

headers = {
    'x-rapidapi-host': "unogs-unogs-v1.p.rapidapi.com",
    'x-rapidapi-key': "8c3ee30dfcmsh1b2042bd6f9f5e1p1fcd92jsn6ffac72ad451"
    }

conn.request("GET", "/search/titles?type=movie&title=Breaking%20Bad&order_by=title", headers=headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))

# Results

{
    "Object": {
        "total": 136,
        "limit": 100,
        "offset": 0
    },
    "results": [
        {
            "title": "10 Cloverfield Lane",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABSnumtTmgLPbFO-PCIJ8TRgXYsUkbeemJsMLbaxEbmt0bYf_YX9_R1ADggWVpOi6G_39WNGyoD_ttxQJ64zuBxqlxg.jpg?r=5e4",
            "title_type": "movie",
            "netflix_id": 80082850,
            "synopsis": "After breaking up with her fiancé, a woman has an accident and wakes up in a bunker with a man who convinces her there&#39;s been an apocalyptic event.",
            "rating": "3.4195116",
            "year": "2016",
            "runtime": "6213",
            "imdb_id": "tt4950600",
            "poster": "N/A",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-11-25"
        },
        {
            "title": "A Bad Moms Christmas",
            "img": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAAAenaohvwZnWtMWD8Chw6-Q6N8Cdz2_qevd5TohUTZVEyn6ycBsGzswCexDIVuHvj5glXZbrJ3A-KZhoR6E4bsqbvNA.jpg?r=ad6",
            "title_type": "movie",
            "netflix_id": 80177872,
            "synopsis": "Stressed-out moms Amy, Carla and Kiki are back, and the looming Christmas holiday gets even more daunting when their mothers show up for a visit.",
            "rating": "0",
            "year": "2017",
            "runtime": "6268",
            "imdb_id": "tt6359956",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTUwNTA4MDMxNl5BMl5BanBnXkFtZTgwMjE4NjQ0MzI@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-01-06"
        },
        {
            "title": "A Bad Son",
            "img": "https://occ-0-2968-778.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcSLXDENMGIXq6ykiG_mFPSD8fYFjZImJlFQDOGuRhmckW2hM2YtWiDaUiYzBWLUGuV2rm5rtKp-UW3HzSy28-CJqA.jpg?r=ae8",
            "title_type": "movie",
            "netflix_id": 81409740,
            "synopsis": "After his release from prison, Bruno attempts to rebuild his life but struggles to please his dad and falls for a woman recovering from addiction.",
            "rating": "0",
            "year": "1980",
            "runtime": "6541",
            "imdb_id": "tt0081678",
            "poster": "https://m.media-amazon.com/images/M/MV5BMGQwY2FlNTQtZjc5Zi00MTk4LThlZTYtNWZiMjQ5Mzc4MjZiXkEyXkFqcGdeQXVyNzgzODI1OTE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2022-02-12"
        },
        {
            "title": "A Coffee in Berlin",
            "img": "https://occ-0-1007-1361.1.nflxso.net/art/47c8e/f3db54d206ec8bc600eeba2f216c7c2eee847c8e.jpg",
            "title_type": "movie",
            "netflix_id": 70261537,
            "synopsis": "Stuck in a rut of bad luck, a college dropout wanders around the streets of Berlin, crossing paths with a slew of eccentric characters.",
            "rating": "3.4623816",
            "year": "2012",
            "runtime": "5099",
            "imdb_id": "tt1954701",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNDgzOTQxNzU1MV5BMl5BanBnXkFtZTgwNzE3MzM4MTE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "A Dozen Summers",
            "img": "https://occ-0-2851-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABV7qTqVduzH61N4Fwh4jh1vqnTnn8VHoHHn8Wf_n_tGsG_4-hgP-x4vRY4dA780sXx0ySj-1BGGbJs9n_X2Y9JnyBw.jpg?r=fe9",
            "title_type": "movie",
            "netflix_id": 81409039,
            "synopsis": "Twelve-year-old twin sisters hijack a children&#39;s movie to tell their own story, where they battle bullies, go on bad dates and set their dad up.",
            "rating": "0",
            "year": "2015",
            "runtime": "4874",
            "imdb_id": "tt3533254",
            "poster": "https://m.media-amazon.com/images/M/MV5BMjM3OTI2MzU2M15BMl5BanBnXkFtZTgwNzgyOTgyNjE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-12-10"
        },
        {
            "title": "A Guy and a Gal",
            "img": "https://occ-0-2851-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXCWXJ3q_FjXHZnFlyK-pKLXudnfxlK1u1ArKX2qSkePtuMIVfurS9Btfk6BL9c2MzzjKCBJKoHGfq9d-tsmbcORFQ.jpg?r=f18",
            "title_type": "movie",
            "netflix_id": 81382089,
            "synopsis": "A hypochondriac, unlikely Casanova and unmotivated journalist struggles to give up his bad habits when he falls in love with an ambitious woman.",
            "rating": "0",
            "year": "1975",
            "runtime": "5597",
            "imdb_id": "tt0073239",
            "poster": "https://m.media-amazon.com/images/M/MV5BNDUzZDkzNTktNTUyMC00YzVhLThhY2ItNGNiZGMyNWYzMDJmXkEyXkFqcGdeQXVyNzQxNDExNTU@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-03-26"
        },
        {
            "title": "A Walk to Remember",
            "img": "https://occ-0-34-32.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYPKQNuCNNPs7vFWYYZYWpvN5LOBBpXVJnZX4t7BCfmROE4PYOfVEMVYIR_9E45o0OEEmURftY78dIsvMzTHnGeqMw.jpg?r=a22",
            "title_type": "movie",
            "netflix_id": 60022589,
            "synopsis": "When bad boy Landon is cast opposite the campus bookworm in a school play, romance blooms -- but ultimately, tragedy tears them apart.",
            "rating": "3.9221668",
            "year": "2002",
            "runtime": "6119",
            "imdb_id": "tt0281358",
            "poster": "http://ia.media-imdb.com/images/M/MV5BMTM1MTYzNjA3M15BMl5BanBnXkFtZTcwMjk2NTE4Mg@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "After",
            "img": "https://occ-0-768-769.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABeh0cBuvhnEnLugquQUgv5scHYtHh9aU0xuLHEomKa4sBmlvRn_ZMyIaecHBVe7w9bb9KcaGKoePmIuP0EW7aDlxsw.jpg?r=27b",
            "title_type": "movie",
            "netflix_id": 80244311,
            "synopsis": "Wholesome college freshman Tessa Young thinks she knows what she wants out of life, until she crosses paths with complicated bad boy Hardin Scott.",
            "rating": "0",
            "year": "2019",
            "runtime": "6358",
            "imdb_id": "tt4126476",
            "poster": "https://m.media-amazon.com/images/M/MV5BOGUwMjk3YzktNDI0Yy00MzFiLWFjNmEtYTA2ODVjMzNhODhjXkEyXkFqcGdeQXVyOTQ1MDI4MzY@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-07-12"
        },
        {
            "title": "Alissa",
            "img": "https://occ-0-4039-1500.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYpJAcapmVhUUfW5ZibWOL2tWCwHjVYs9bcPqyJ8xo5zFEha0zBxK3k9aMhSESrGCYs8tBRqxUUakKwl5f4VIja49A.jpg?r=f1e",
            "title_type": "movie",
            "netflix_id": 81409292,
            "synopsis": "After breaking into his dad&#39;s house, Luc becomes entangled in a double murder and encounters a Lithuanian woman, who draws him into a wider plot.",
            "rating": "0",
            "year": "1998",
            "runtime": "5668",
            "imdb_id": "tt0118584",
            "poster": "https://m.media-amazon.com/images/M/MV5BODk4MzlhOWItOTVmMS00N2FmLWI1M2QtMzYzYjg3MjEwYmNiXkEyXkFqcGdeQXVyMjc1NDA2OA@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-12-01"
        },
        {
            "title": "As Tears Go By",
            "img": "http://cdn0.nflximg.net/images/3578/2273578.jpg",
            "title_type": "movie",
            "netflix_id": 70012877,
            "synopsis": "A Hong Kong gangster does all he can to keep his pal and fellow mobster out of trouble, but their crime boss is close to reaching his breaking point.",
            "rating": "3.0554848",
            "year": "1988",
            "runtime": "5962",
            "imdb_id": "tt0096461",
            "poster": "http://ia.media-imdb.com/images/M/MV5BOTQyNDQwOTQ4MV5BMl5BanBnXkFtZTcwNzAxMjcyMQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Baby Driver",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABeRyzaDtUuhFM7NNQfE2JGrziIKc_8ICoFW6a22xxYgakwXr2jRLexdAC6XQgvXLb4aeFVjXYmKps0_FMC19WQrKPg.jpg?r=c6b",
            "title_type": "movie",
            "netflix_id": 80142090,
            "synopsis": "Smooth-faced getaway driver Baby is a music junkie in deep with a bad dude. He&#39;s got just one job left, but it&#39;s all about to go sideways.",
            "rating": "0",
            "year": "2017",
            "runtime": "6780",
            "imdb_id": "tt3890160",
            "poster": "https://m.media-amazon.com/images/M/MV5BMjM3MjQ1MzkxNl5BMl5BanBnXkFtZTgwODk1ODgyMjI@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-10-01"
        },
        {
            "title": "Back to the Outback",
            "img": "https://occ-0-3498-2567.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZa9tWHpO6ZifPD5lS0Jwo9bnlDD6XGJIC5ARVwRfglP5l6SFYyThd5fczY2XxjDx3bcZGecOnLRNdhs7mht0pN9eJiN182ALODpIHqBTwzca8P0eCEkeqjXS1o.jpg?r=2ab",
            "title_type": "movie",
            "netflix_id": 81002813,
            "synopsis": "They might look dangerous, but these wildly misunderstood creatures have hearts of gold — and they’re breaking out of captivity on a quest to find home.",
            "rating": "0",
            "year": "2021",
            "runtime": "5741",
            "imdb_id": "tt13575806",
            "poster": "https://m.media-amazon.com/images/M/MV5BMmU0YzExYjctOGM0Yy00NzdkLTgxOGEtYjAwNzcxZGY4YTBiXkEyXkFqcGdeQXVyMTEzMTI1Mjk3._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-12-10"
        },
        {
            "title": "Bad Blood",
            "img": "https://occ-0-1433-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABX49MyGfCXT_VMHX0r5cEw-S35VGLZB7r5DIbdPNel6OH87BA1WX4QKKcNvp1SxQG43eBWzoUHVvLeXGLM8WX8X6HQ.jpg?r=20b",
            "title_type": "movie",
            "netflix_id": 81558113,
            "synopsis": "In a Turkish border town, a merchant strives to keep the peace, preserve his power and prepare his sons to become leaders in their community.",
            "rating": "0",
            "year": "2021",
            "runtime": "6132",
            "imdb_id": "tt6423364",
            "poster": "https://m.media-amazon.com/images/M/MV5BMzRmNzZkMmMtMzU5YS00ZThhLWE2YzItZTNhNGMwMmI1MjQyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2022-01-17"
        },
        {
            "title": "Bad Boy",
            "img": "https://occ-0-2506-1432.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABViSMM2lInigpF0rIgIFbTCyzkBn8X__mAlZb76u-bdif_mnV2TaZafOhmkkrWr9S2H3BZx_muh238NfW59JCKmWVA.jpg?r=064",
            "title_type": "movie",
            "netflix_id": 81273580,
            "synopsis": "A soccer club owner goes to vicious — and criminal extremes — to build a top team, with shocking results on and off the field. Inspired by real events.",
            "rating": "0",
            "year": "2020",
            "runtime": "6572",
            "imdb_id": "tt11720240",
            "poster": "https://m.media-amazon.com/images/M/MV5BYTg2OWIyZDEtMTZlOC00ZWQ3LTgyNmYtOWUzMjQ2NWQxYTM4XkEyXkFqcGdeQXVyNTM0MDc1ODE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-04-09"
        },
        {
            "title": "Bad Boy Bubby",
            "img": "https://occ-0-3345-2568.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABaJNBjbX27jHT1eXqhEJ-VyezpJpVyuOqqsmF2dgkzSXaEmoAgtyBXaZZEYmnYiqCYALuAs0EBCjjaA9z24dp8vqBg.jpg?r=365",
            "title_type": "movie",
            "netflix_id": 70027226,
            "synopsis": "Sequestered from civilization since birth, Bubby is deemed \"a bad boy\" by his mother, who&#39;s kept him indoors by telling him he&#39;ll die outside.",
            "rating": "0",
            "year": "1993",
            "runtime": "6846",
            "imdb_id": "tt0106341",
            "poster": "https://m.media-amazon.com/images/M/MV5BMTQwNzczMjg3OV5BMl5BanBnXkFtZTcwODg1NzgyMQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-05-05"
        },
        {
            "title": "Bad Boys",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABebqcnaJ39h8DPgObwIcIvDbWFbp6gVXu0g9q4QWsmR5ScarfjQqMdt114Lam4GF0AoQ6-KyqpQUha5N4Zr4Rvya6A.jpg?r=7ef",
            "title_type": "movie",
            "netflix_id": 269880,
            "synopsis": "In this fast-paced actioner, two Miami narcotics cops are hot on the trail of a master crook who has snatched $100 million worth of heroin.",
            "rating": "3.8355026",
            "year": "1995",
            "runtime": "7147",
            "imdb_id": "tt0112442",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY4NDk1NTU5NF5BMl5BanBnXkFtZTcwMjE2NDU2MQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Bad Boys for Life",
            "img": "https://occ-0-299-1007.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZEb6xT3cK6UHbKcFI4Pzw3rFQDbO-AoAOezXuFn_OFa1G-42FrjF4oWxwTrQtMPNzMFEybc3uMSZNK5nHktb_HZ0MF0s-GDve_U-vOykSZWAJ8dF4Yp9XyeGVDwiecqelgOjJjGjBcrOqyc3OIN18Fc_g.jpg?r=0ca",
            "title_type": "movie",
            "netflix_id": 81152992,
            "synopsis": "Even bad boys grow up, and Miami cop Marcus is ready for his well-deserved retirement â€” until partner Mike is targeted by a cutthroat drug cartel.",
            "rating": "0",
            "year": "2020",
            "runtime": "7436",
            "imdb_id": "tt1502397",
            "poster": "https://m.media-amazon.com/images/M/MV5BMWU0MGYwZWQtMzcwYS00NWVhLTlkZTAtYWVjOTYwZTBhZTBiXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-08-01"
        },
        {
            "title": "Bad Boys II",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTcTkKiicE6T7qRsD00PzUEVHrV4VVcFJYvxSpV_p21s-RfdrFuV6NolCLJs6ox272ReCO-ABsuzIU4tBNKwsmeOIg.jpg?r=abf",
            "title_type": "movie",
            "netflix_id": 60029167,
            "synopsis": "In this hyperkinetic sequel, a pair of Miami narcotics cops investigate a Cuban drug kingpin&#39;s connection to Florida&#39;s influx of Ecstasy.",
            "rating": "3.764312",
            "year": "2003",
            "runtime": "8810",
            "imdb_id": "tt0172156",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZmU4NzVkZjEtZmQxMi00ZDY5LWI3ZDYtMWRmZjE5YmYwZjQzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Bad Education",
            "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWc89BqwLzSEwn8SQ4xu8EdWGZ9qMNsVyCHkE3uTOl8FS-URaUDcAPGLHEcZ4GQ-eb86-84jVYLNiGTT7w95OAM51A.jpg?r=14c",
            "title_type": "movie",
            "netflix_id": 70011205,
            "synopsis": "A film director reunites with his childhood friend, who shares a short story he&#39;s written about being molested by their Catholic school teacher.",
            "rating": "0",
            "year": "2004",
            "runtime": "6309",
            "imdb_id": "tt0275491",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMmFjNWU1YjMtOWVhZC00OGI4LTgwN2UtNDQ1ODMxZGZmZTFmXkEyXkFqcGdeQXVyMTA0MjU0Ng@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-12-15"
        },
        {
            "title": "Bad Faith",
            "img": "https://occ-0-4039-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZOWASUHUEmQ39bdZyGlGq-cpqILdvNut_3Glg5Jd-M1qoImPI1tMqsNWd5ENkEQBYCvENc629t_Iiwagw3kgfF_ew.jpg?r=d81",
            "title_type": "movie",
            "netflix_id": 81409229,
            "synopsis": "When Clara becomes pregnant, she and her lover, Ismaël, move in together. But their respective Jewish and Muslim families don&#39;t take the news well.",
            "rating": "0",
            "year": "2006",
            "runtime": "5254",
            "imdb_id": "tt0190994",
            "poster": "https://m.media-amazon.com/images/M/MV5BMTY1NDc5MDMyOF5BMl5BanBnXkFtZTcwMTY2MjcxMQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-11-03"
        },
        {
            "title": "Bad Faith",
            "img": "http://cdn0.nflximg.net/images/7814/11907814.jpg",
            "title_type": "movie",
            "netflix_id": 70153554,
            "synopsis": "When recent emigrant Monia finds a victim of the so-called &#39;Bayonet Killer&#39; lying bleeding in the streets, her mix of horror and fascination with the murderer&#39;s brutal methods inspires her to moonlight as an amateur detective.",
            "rating": "2.179318",
            "year": "2010",
            "runtime": "6096",
            "imdb_id": "tt1373454",
            "poster": "http://ia.media-imdb.com/images/M/MV5BMTU0MTE3NzIwMF5BMl5BanBnXkFtZTcwMzIyOTY3Mw@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Bad Genius",
            "img": "https://occ-0-64-325.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABd03iIKmVpCmsahB_y1iddxm06PO8yL_VkxRTblGFWwDSa_jc-kyhhoIT9dui5aD_5fAbzldAty-LV8nao63iDpmlQ.jpg?r=167",
            "title_type": "movie",
            "netflix_id": 80245442,
            "synopsis": "A top student gets pulled into a cheating racket with increasingly higher risks and even higher rewards. But she may lose much more than she gains.",
            "rating": "0",
            "year": "2017",
            "runtime": "7779",
            "imdb_id": "tt6788942",
            "poster": "https://ia.media-imdb.com/images/M/MV5BMzMxMTFlMDYtNjIyNS00YzQ4LWJlMDAtNGQwY2RlZGJiMmM1XkEyXkFqcGdeQXVyNzEyMTA5MTU@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-06-01"
        },
        {
            "title": "Bad Grandpa .5",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTbiwkSlUe7zpiLk1FyFQJ9jKPlFEToA3T7G-DLLXr6kJluOOipnUUZJj0jEoHS61w0shP9zFRYCmRDU7dgjlaQGCA.jpg?r=91c",
            "title_type": "movie",
            "netflix_id": 70308046,
            "synopsis": "The geriatric antics of Irving Zisman continue in this next installment of the Jackass franchise, which features unused footage from the first film.",
            "rating": "3.5731573",
            "year": "2014",
            "runtime": "5177",
            "imdb_id": "tt3766424",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNjIwMjI2Mjg2Nl5BMl5BanBnXkFtZTgwMTQ1MjM5MTE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Bad Hair",
            "img": "https://occ-0-1174-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUW7yosHo9sLj3Hwr3xUq5SoeBzhG0CcsTn_FYm5nnSXEbNYqe2q6l5LO9sm_kh_oBvbm_nanpd5MzVXoM0PL-8IBA.jpg?r=003",
            "title_type": "movie",
            "netflix_id": 81012138,
            "synopsis": "At a TV network in 1989, an aspiring VJ is pressured into getting a weave. Her new hair could help her get ahead – if it didn&#39;t have a mind of its own.",
            "rating": "0",
            "year": "2020",
            "runtime": "6146",
            "imdb_id": "tt4798836",
            "poster": "https://m.media-amazon.com/images/M/MV5BMzNiYzUxMDItNTI3Yy00OWI4LWEyZWUtNDhmODVkOTJkZjI5XkEyXkFqcGdeQXVyNjY1MTg4Mzc@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-10-05"
        },
        {
            "title": "Bad Investigate",
            "img": "https://occ-0-2744-2706.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRD0UTLJPGqa9h_WNyfKoTWTU5eDpbu3tSG3nd0M9p37pP9wmLtCGgORpG2SY6wfwbwIMJO5kcU-YJfSEdDjm3yDgA.jpg?r=9d8",
            "title_type": "movie",
            "netflix_id": 81428718,
            "synopsis": "A corrupt police officer hires two men to track down a notorious — and extremely dangerous — criminal, who has an agenda of his own.",
            "rating": "0",
            "year": "2018",
            "runtime": "7396",
            "imdb_id": "tt6610280",
            "poster": "https://m.media-amazon.com/images/M/MV5BYTQ4MjQyOGMtZGJlYS00ZTIzLWE1YTItM2RjODAwNDBmMTUzXkEyXkFqcGdeQXVyMjM0OTY5ODg@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-05-21"
        },
        {
            "title": "Bad Moms",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABaaRjg9lVDYU3aZFd3uME2U7dkz-sk4cxkoYxZc6YEu1xw4VzxB6p3h8sbb9dypBts2UZRdxiaPy0E7BVASsH_8M6A.jpg?r=1f4",
            "title_type": "movie",
            "netflix_id": 80100906,
            "synopsis": "When newly single mother Amy snaps under the weight of responsibility, two other burned-out moms join her on a raunchy spree of bad behavior.",
            "rating": "3.4806116",
            "year": "2016",
            "runtime": "6031",
            "imdb_id": "tt4651520",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjIwNzE5MTgwNl5BMl5BanBnXkFtZTgwNjM4OTA0OTE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-12-13"
        },
        {
            "title": "Bad Neighbours 2",
            "img": "https://occ-0-768-769.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYwo39vvRPLJmFip8BroA9Ny7X62ktC1NZ_-1Xe1NQls6OY3ED9FEq5EHTGvB3CM7lgadUQ91Wk6KKJ6uUcRSPIzyg.jpg?r=236",
            "title_type": "movie",
            "netflix_id": 80091747,
            "synopsis": "When a sorority with a progressive agenda moves in next door, parents Mac and Kelly must keep them at bay before closing the deal on their house sale.",
            "rating": "0",
            "year": "2016",
            "runtime": "5540",
            "imdb_id": "tt4438848",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY0NzUxMDUzN15BMl5BanBnXkFtZTgwNzI2MTY4ODE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-02-08"
        },
        {
            "title": "Bad Samaritan",
            "img": "https://occ-0-768-769.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABT6rsSYudiIr73e4Aftgzpi_ALrUKeJJAngdXnMxF2Xnv4XdwVMkNbxdfp8yHLc-sMdG5qsZJ6GXV1Z9oPaR9oqjVQ.jpg?r=c2c",
            "title_type": "movie",
            "netflix_id": 80243042,
            "synopsis": "An attempted burglary morphs into a psychotic chase when a young scam artist breaks into a twisted torturer&#39;s home and finds a woman being held captive.",
            "rating": "0",
            "year": "2018",
            "runtime": "6605",
            "imdb_id": "tt3203528",
            "poster": "https://m.media-amazon.com/images/M/MV5BNTk3NWI3NTktMjBkYi00OGJlLWE1MmItNjlkZTExMTZmZDdhXkEyXkFqcGdeQXVyMjU4ODU0MzU@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-02-28"
        },
        {
            "title": "Bad Santa",
            "img": "https://occ-0-784-778.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZKyFYfD3X64o0wNW_oPp7oUcTSFHUqxGQsFEsnTc6F8DtXEFjJoyGH0Qc6ZjL6AWm7v3ktwomNc0OxdFXyyd4TbWQ.jpg?r=e53",
            "title_type": "movie",
            "netflix_id": 60031267,
            "synopsis": "Criminals Willie and Marcus disguise themselves as Santa Claus and an elf and find work at major department stores with plans of robbing them blind.",
            "rating": "3.502354",
            "year": "2003",
            "runtime": "5978",
            "imdb_id": "tt0307987",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA4Njg1MDcwN15BMl5BanBnXkFtZTYwMzAxNjM3._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Bad Santa 2",
            "img": "https://occ-0-1490-1489.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABb5gWKGoh0rgC5Y4EtxwU8MrtFpyeHvZNUzyiMHsMJK7UioRTLT2PyAipVm8CNimC49uQMmhUSZcU5Iv318BsTA3bg.jpg?r=4aa",
            "title_type": "movie",
            "netflix_id": 80112360,
            "synopsis": "Sad-sack Santa Willie Soke isn&#39;t known for doing the right thing. Now, with help from his mom, he&#39;s about to take his act to a whole new level of bad.",
            "rating": "0",
            "year": "2016",
            "runtime": "5536",
            "imdb_id": "tt1798603",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjM2MjE5Mzc4OF5BMl5BanBnXkFtZTgwMjc3NjEyMDI@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-07-01"
        },
        {
            "title": "Bad Seeds",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfF8X7WGn4kS9SPHEeBP_QZQbV2uHOwSg_UlW-VlF0hpKjhEhu-T1Jk2b-pWkKzTjbg-eAkwqAO4_Pk_oTkKRIk4ZQ5by76jJsmNdjeEio6fEMRXTx7A7tPt5RU.jpg?r=117",
            "title_type": "movie",
            "netflix_id": 80999643,
            "synopsis": "Troubled by his past, a scam artist who runs a petty racket with his adoptive mom finds redemption while mentoring a group of difficult students.",
            "rating": "0",
            "year": "2018",
            "runtime": "6318",
            "imdb_id": "tt6708116",
            "poster": "https://m.media-amazon.com/images/M/MV5BZDBhZTg2ZGItMjQ4ZC00NmNkLTg5NGYtMzE1ZGU0N2JiMjIyXkEyXkFqcGdeQXVyNTc5OTMwOTQ@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-12-21"
        },
        {
            "title": "Bad Teacher",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXQGIoiXIjfZj5jhcMOh16S0iXdEY089FhXmrcQvr2mnsmxXN0rU506eBaUG8vMNBfJS5LwQ6-patN1yFvBCiPfRVQ.jpg?r=321",
            "title_type": "movie",
            "netflix_id": 70141587,
            "synopsis": "When a scheming and coarse-tongued teacher gets dumped by her wealthy boyfriend, she rebounds by sinking her claws into a handsome substitute teacher.",
            "rating": "3.3635223",
            "year": "2011",
            "runtime": "5516",
            "imdb_id": "tt1284575",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTQ5NDI4MDM0Nl5BMl5BanBnXkFtZTcwNDYwODU2NA@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Bad Trip",
            "img": "https://occ-0-4039-1500.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcdCsO1Y0hO1o4o_AyF4ET-mhsGtLJc-ugr_jTgoONs05B15Um2VbTQWQuIAw9e-2_wpJQe0EW3dX19sfH5Zgq4ER-NKkyEki_wT-2eoDvsEs4DWpfu0pJxnwIY.jpg?r=3d4",
            "title_type": "movie",
            "netflix_id": 81287254,
            "synopsis": "In this hidden-camera prank comedy, two best friends bond on a wild road trip to New York as they pull real people into their raunchy, raucous antics.",
            "rating": "0",
            "year": "2021",
            "runtime": "5205",
            "imdb_id": "tt9684220",
            "poster": "https://m.media-amazon.com/images/M/MV5BNDgzMTgxOTktNmM2Ny00Nzk5LTgxNjAtNzJlNjBjNjMyOWZkXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-03-27"
        },
        {
            "title": "Batman: The Killing Joke",
            "img": "https://occ-0-2430-2433.1.nflxso.net/art/b2196/3582be3326fe411572c95f79040986bb159b2196.jpg",
            "title_type": "movie",
            "netflix_id": 80107414,
            "synopsis": "The Joker makes life hell for the Gordon family in a monstrous attempt to prove to Batman that one bad day can drive a good man to madness.",
            "rating": "3.2481654",
            "year": "2016",
            "runtime": "4595",
            "imdb_id": "tt4853102",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTdjZTliODYtNWExMi00NjQ1LWIzN2MtN2Q5NTg5NTk3NzliL2ltYWdlXkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-02-09"
        },
        {
            "title": "Benchwarmers 2: Breaking Balls",
            "img": "https://occ-0-2219-2218.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABU1TYKSvu7gyohYEf_RkSw1sGmK49oPBQTOoGTXLkVjaJhvgrOH-j9WcQgKZYUuuznmIDBStrCKklaTtnAiIrYbcpw.jpg?r=333",
            "title_type": "movie",
            "netflix_id": 81038225,
            "synopsis": "A rookie lawyer with an emasculating past in baseball can break into the legal world only if he manages a law firm&#39;s ragtag company softball team.",
            "rating": "0",
            "year": "2019",
            "runtime": "5419",
            "imdb_id": "tt8750122",
            "poster": "https://m.media-amazon.com/images/M/MV5BNzdjZTExMGUtNjdiZi00OTY3LTk0NTgtYWQ1ZmNjYThkZWI1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-12-31"
        },
        {
            "title": "Birds of Prey (And the Fantabulous Emancipation of One Harley Quinn)",
            "img": "https://occ-0-3467-3466.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXEAg-862dYMLYCm_Bv1U4f-YUrJh-h-PW3Ck08FxCCmPhRPuAw7vCOnliJIr1sIL1_Exn0CFnpw-ouHQC69HuqIlcrrSlBM2JcaJA8DiRWOlJ6xyX7bUt0o548JW_ttm4kWJ1DWt6G35fz3zlDkR8xCJQ.jpg?r=0ab",
            "title_type": "movie",
            "netflix_id": 81165134,
            "synopsis": "After breaking it off with the Joker, Harley Quinn becomes a target till she teams up with an all-women superhero squad to battle a crime kingpin.",
            "rating": "0",
            "year": "2020",
            "runtime": "6530",
            "imdb_id": "tt7713068",
            "poster": "https://m.media-amazon.com/images/M/MV5BMzQ3NTQxMjItODBjYi00YzUzLWE1NzQtZTBlY2Y2NjZlNzkyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-11-27"
        },
        {
            "title": "Bon Cop Bad Cop 2",
            "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYFbuhCXLAlcVvlhG6nu0amWhr6ITXhl8IlD2KWoRFbp3pTX0lcOPT36vGz_QDI02WlMmPYsbXIlwa1aW9KyFk_qnw.jpg?r=e83",
            "title_type": "movie",
            "netflix_id": 80131563,
            "synopsis": "Two veteran buddy cops are back for a second chapter, this time to tackle a car theft ring that turns out to be much more than they bargained for.",
            "rating": "0",
            "year": "2017",
            "runtime": "7575",
            "imdb_id": "tt4738174",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNjE2YjVhN2YtZGNjNi00ZWFlLWFjMTAtOTBiODU4MTYxMmI5XkEyXkFqcGdeQXVyMzYxNDc5MA@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-11-11"
        },
        {
            "title": "Bon Cop, Bad Cop",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUD4c0ySHYWWdH0J9yDCiFzvSOMJwuwqq3C8fpIRaE_zY4IxMn50w6IEg-ajgBaGuu0x_SgGeSgB1QmaDsc6BDUrfw.jpg?r=ed1",
            "title_type": "movie",
            "netflix_id": 70095265,
            "synopsis": "This action comedy shows what happens when two cops with opposing ideologies -- an English-speaking officer from Toronto and a French-speaking one from Montreal -- are forced to work together to solve a crime.",
            "rating": "3.0762224",
            "year": "2006",
            "runtime": "6996",
            "imdb_id": "tt0479647",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU2NTkwMTcwM15BMl5BanBnXkFtZTcwNzIwNzE0MQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-03-04"
        },
        {
            "title": "Breaking In",
            "img": "https://occ-0-1926-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXFmP9eQz1TG3iWbLjmnekA2oTDNEd6iB2AbSneGnn2d2MmcsryEL_wpqo1Uye_UxPVC3otsDoQiLtt5KvI8vl_E2Q.jpg?r=bca",
            "title_type": "movie",
            "netflix_id": 80237992,
            "synopsis": "A mother turns the tables on a group of robbers who have kidnapped her kids inside a fortified house.",
            "rating": "0",
            "year": "2018",
            "runtime": "5277",
            "imdb_id": "tt7137846",
            "poster": "https://m.media-amazon.com/images/M/MV5BNTQwNjc3NjE5MF5BMl5BanBnXkFtZTgwNTEzMDg5NDM@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-05-11"
        },
        {
            "title": "Breaking News",
            "img": "https://occ-0-1391-2773.1.nflxso.net/dnm/api/v6/1lcgfy_NA26l7dfd356LqCUdNPM/AAAABbQZGOzTKwBwsWz8jujOk-kUd1_Quhxh0TdcuQ1pDe1Vn9jaSRl3iAgjCn6UyMxzHbPXoY-VeTYG8D-BQjZIgJg75YPWs_03NnhGA_3bbxkDUac.jpg?r=dc8",
            "title_type": "movie",
            "netflix_id": 81323777,
            "synopsis": "With dreams of becoming a primetime news anchor, a reporter becomes a war correspondent and takes on risky assignments exposing corruption.",
            "rating": "0",
            "year": "2000",
            "runtime": "7543",
            "imdb_id": "tt0414931",
            "poster": "https://m.media-amazon.com/images/M/MV5BMDNlOTY1ZTYtYWU1Ny00MDVmLWE5Y2EtNjk4YWVjNmE5MGViXkEyXkFqcGdeQXVyNjc1MzY5NDU@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-02-02"
        },
        {
            "title": "Breaking News",
            "img": "https://occ-0-3467-3466.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYlm0fM0K0-JDZM0YCxlfCD5x5P4h3R3w8kjm1LcgoLpxOygtRIXeAQIZ9Is2-sPIj6N-zaKkLJrSGQscdnBUBGGsA.jpg?r=e65",
            "title_type": "movie",
            "netflix_id": 81149201,
            "synopsis": "A well-known reporter is tasked to eulogize a deceased colleague and becomes engrossed in mending the man’s estranged relationship with his daughter.",
            "rating": "0",
            "year": "2017",
            "runtime": "4845",
            "imdb_id": "tt6957004",
            "poster": "https://m.media-amazon.com/images/M/MV5BYWJmOTEzZDUtMmNjYi00OTc0LWI3MjEtMjlmMmZlNTZlMTM2XkEyXkFqcGdeQXVyNDkzNTM2ODg@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-08-21"
        },
        {
            "title": "Breaking News in Yuba County",
            "img": "https://occ-0-762-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABc_u8Dnbr8fuHWrdQgmINJCnqQEb3kLk-i3ABu1pjnf5q1Mr8kl5rYNoDa11bAU-mqs2rxRhKJ111uHjXUUKEhdm1g.jpg?r=715",
            "title_type": "movie",
            "netflix_id": 80995453,
            "synopsis": "After her cheating husband dies of a heart attack, a neglected and lonely wife buries him, reports him missing and takes advantage of the limelight.",
            "rating": "0",
            "year": "2021",
            "runtime": "5771",
            "imdb_id": "tt7737640",
            "poster": "https://m.media-amazon.com/images/M/MV5BMWJkMTg1NWUtN2E0Yy00Y2M4LWEyMjItMjQ4ZDBiYmY3ZWIyXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-10-23"
        },
        {
            "title": "Breaking Surface",
            "img": "https://occ-0-395-988.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABbrUPmyTg8Z98KnnrJ5cM2QXTsC5Pkwmyonbxp1_k5wnwoRVFMtCpKpuwS4vcDPJ9X4hbjb2pUzXq30KQ7VMoqhkNQ.jpg?r=7cd",
            "title_type": "movie",
            "netflix_id": 81553959,
            "synopsis": "When two sisters set out on a winter dive in a Norwegian fjord, they must race against time when one of them gets trapped at the bottom of the sea.",
            "rating": "0",
            "year": "2020",
            "runtime": "4893",
            "imdb_id": "tt10081762",
            "poster": "https://m.media-amazon.com/images/M/MV5BMTA5YzNhMjgtZGEyZi00Nzg5LWE1ZTUtYzc1ZmMyMWNmOTMzXkEyXkFqcGdeQXVyMTAzNDgzMjU1._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-12-27"
        },
        {
            "title": "Breaking the Bank",
            "img": "https://occ-0-2219-2218.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZF4YnrJCAzF5oP2y5mvNb3dWzxAELqe_SC8UrU0CFq0DRfo_DqC4UIZfMvc7_DlpxBzgkO94ZAX05DO0xlZ3AHUpA.jpg?r=ff8",
            "title_type": "movie",
            "netflix_id": 80108158,
            "synopsis": "Bank chairman Charles Bunbury -- who knows next to nothing about banking -- fights to save both his company and his marriage from disaster.",
            "rating": "0",
            "year": "2014",
            "runtime": "6300",
            "imdb_id": "tt3105662",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZDBjY2JiN2UtZmU3Zi00ZTFmLWJiZDUtMGY2OTUzNWM3YTU1XkEyXkFqcGdeQXVyMTU4MjA4ODI@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-03-02"
        },
        {
            "title": "Burnt",
            "img": "https://occ-0-753-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfWcpM4YKjklrB9QIgrJnUJR0YBzv5SROPKlwYg9vM4UnGYcUtsvPOahgWkCKrS1MrLWA-qwRENzZilIfiZvGyX2-g.jpg?r=322",
            "title_type": "movie",
            "netflix_id": 80048561,
            "synopsis": "A chef who destroyed his career through recklessness and bad behavior comes to London to redeem himself and regain his former glory.",
            "rating": "0",
            "year": "2015",
            "runtime": "6058",
            "imdb_id": "tt2503944",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNjEzNTk2OTEwNF5BMl5BanBnXkFtZTgwNzExMTg0NjE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-08-30"
        },
        {
            "title": "Carlito&#39;s Way",
            "img": "https://occ-0-1168-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABam9mvnPjaI9H9Ejq8Rphs7XAuca3DV0u47MgpXoeG02T0yCZKBIPz-HIxO1QjnIxqIofTmvPL2ySJzdJ1e0ksX7jg.jpg?r=ce5",
            "title_type": "movie",
            "netflix_id": 351701,
            "synopsis": "Sprung from prison, Carlito Brigante vows to use his unexpected second chance to go straight. But as hard as he tries, the bad guys pull him back in.",
            "rating": "3.8634603",
            "year": "1993",
            "runtime": "8644",
            "imdb_id": "tt0106519",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZmQ1ZDc0MDAtNjVmYi00MDkxLWE5MDItZmJmNjcxZGEyMWRjXkEyXkFqcGdeQXVyNjUwNzk3NDc@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-10-01"
        },
        {
            "title": "Chic!",
            "img": "http://art-1.nflximg.net/f600c/e4778977f840c3c965f63b038e9aecc11f9f600c.jpg",
            "title_type": "movie",
            "netflix_id": 80045662,
            "synopsis": "A famous designer goes into a slump after a bad breakup, but her ambitious assistant comes to her rescue by finding an unlikely muse to inspire her.",
            "rating": "1.8335974",
            "year": "2015",
            "runtime": "6200",
            "imdb_id": "tt3592176",
            "poster": "http://ia.media-imdb.com/images/M/MV5BNjQ0MjQ4NjI5N15BMl5BanBnXkFtZTgwOTIxMTczNzE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-01-12"
        },
        {
            "title": "Coin Heist",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABeiYpUFpYFGfsbf2N4ikR4ixRkaWyXuedQdObfzOALdr9J97RKKL4zuUO94ERiGB1DwNGs4mtDsp2dwee6EeEnHYi_0rPAEYjLaoSgMVFblZLth2Y9fMU_OEZ1c.jpg?r=077",
            "title_type": "movie",
            "netflix_id": 80097725,
            "synopsis": "When a crisis threatens to destroy their high school, four teens hatch a daring plan to raise $10 million. Step one? Breaking into the U.S. Mint.",
            "rating": "3.56",
            "year": "2017",
            "runtime": "5864",
            "imdb_id": "tt5740806",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNDM4NzhhNTQtZmUyMy00OTFlLWFlMzgtYTQ5OTE3YjBmMTA5L2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyNjczOTE0MzM@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-01-06"
        },
        {
            "title": "Crayon Shin-chan the Movie: Unkokusai&#39;s Ambition",
            "img": "https://occ-0-2772-1007.1.nflxso.net/art/b7159/b9768f882ed4118e35d5e1be89533d80f9bb7159.jpg",
            "title_type": "movie",
            "netflix_id": 80243204,
            "synopsis": "A time traveler claims that bad guys are trying to change the past! Shin-chan is on the case, going back in time to defeat the evil Lord Unkokusai.",
            "rating": "0",
            "year": "1995",
            "runtime": "5771",
            "imdb_id": "notfound",
            "poster": "",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-04-07"
        },
        {
            "title": "Cruise",
            "img": "https://occ-0-531-2705.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABUgC0T0xLfd3cefcFo_naiB7mplLtsiDpPAYcPNJ_Bezda8MRDW3pY8pYubYbyV8Ufz8LSxdTkhHiy94BO0V19eeYg.jpg?r=d8d",
            "title_type": "movie",
            "netflix_id": 81001339,
            "synopsis": "In 1980s New York, a stud with an affinity for hot rods and swiping stereos falls for a privileged college student with a bad girl alter ego.",
            "rating": "0",
            "year": "2018",
            "runtime": "5394",
            "imdb_id": "tt5034122",
            "poster": "https://m.media-amazon.com/images/M/MV5BNzYyMDMwNjYzMF5BMl5BanBnXkFtZTgwODUzMTgxNjM@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-01-30"
        },
        {
            "title": "Dabangg",
            "img": "https://occ-0-2042-299.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYP6_1ZKHCBnCbi_1dnoF8Jq07fJJkp93QLqRysGivWFNxAEGPAokdWAfXGD-vXx_8MmNxmiOijQqz5YxxuIBaWwtA.jpg?r=499",
            "title_type": "movie",
            "netflix_id": 70154586,
            "synopsis": "Bollywood &#39;bad boy&#39; Salman Khan stars as Chulbul Pandey, a corrupt cop who tracks down criminals and takes their money, keeping it for himself. When a new love, Rajo, encourages him to reach out to his estranged family, Chulbul reexamines his life.",
            "rating": "0",
            "year": "2010",
            "runtime": "7541",
            "imdb_id": "tt1620719",
            "poster": "https://m.media-amazon.com/images/M/MV5BMTMyOTQ0Mzg2Ml5BMl5BanBnXkFtZTcwMDcyOTM5NA@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-10-01"
        },
        {
            "title": "Daredevil",
            "img": "http://occ-2-1007-1009.1.nflxso.net/art/a43e8/c1268c0b23063cf2fe3e0dca5bc3d590996a43e8.jpg",
            "title_type": "movie",
            "netflix_id": 60026123,
            "synopsis": "Ben Affleck is Matt Murdock, a Marvel Comics hero who&#39;s a lawyer by day but fights the bad guys at night to avenge the murder of his father, a boxer.",
            "rating": "3.0265665",
            "year": "2003",
            "runtime": "6215",
            "imdb_id": "tt0287978",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjYwZDNhMTgtNjEwNS00Y2Y0LTkxYjMtY2MyYTM0NDE1N2ZlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "David Crosby: Remember My Name",
            "img": "https://occ-0-1007-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABR9RJLN2Lqmvhv8MGOu_hrh-GCKmPwABCh-Hl6EyeTkTz-J6ehyevEalJuCjToAka3S5y_MargD9QQCiYQCKQDswsw.jpg?r=002",
            "title_type": "movie",
            "netflix_id": 81077717,
            "synopsis": "This documentary portrait of David Crosby captures the musical talent, turbulent personality and drug history that made him a bad-boy rock icon.",
            "rating": "0",
            "year": "2019",
            "runtime": "5606",
            "imdb_id": "tt5884004",
            "poster": "https://m.media-amazon.com/images/M/MV5BYjhlNTQyZjItZWU0NS00MmVjLTkxYWItYThlNmJhMTExNjMyXkEyXkFqcGdeQXVyOTgxNDIzMTY@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-06-14"
        },
        {
            "title": "Despido Procedente",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYMxt29xqPrMfWYMlTvQVPq6aJdk73h5TEwYVsC7LW9FbYGt-IPRibWkSe-f6c_a07FGgKo1nGguxsVLAYLboXPk7Q.jpg?r=9a0",
            "title_type": "movie",
            "netflix_id": 80103425,
            "synopsis": "A Spaniard working in Argentina sees his life upended after accidentally giving bad directions to a passerby, who demands compensation for the error.",
            "rating": "0",
            "year": "2017",
            "runtime": "5372",
            "imdb_id": "tt6580972",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzQxMGY4OTItMTU4Yi00MmM1LTgzODEtZWNjNDI4NDAzODU1XkEyXkFqcGdeQXVyMjQ3MDM0NTk@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-01-30"
        },
        {
            "title": "Dogman",
            "img": "https://occ-0-784-778.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcwvbgg3HFVc2Wv8ieyoDkTYp04oyJEyop3qTYxjwZFJm4xRd8mDq3jFMdtAjoveukGmnRC6jLf0wWhsqCpT8nZc1A.jpg?r=179",
            "title_type": "movie",
            "netflix_id": 81006781,
            "synopsis": "When his life hits a breaking point, a meek dog groomer must find a way to free himself from under the thumb of the town bully, a browbeating ex-boxer.",
            "rating": "0",
            "year": "2018",
            "runtime": "5924",
            "imdb_id": "tt6768578",
            "poster": "https://m.media-amazon.com/images/M/MV5BZWIzMmYzNmMtZWNkMy00YzU2LTgzYTQtNDZhMmFmZDkwNTlmXkEyXkFqcGdeQXVyODAzODU1NDQ@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-10-16"
        },
        {
            "title": "Don&#39;t Go Breaking My Heart",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABeLBK8M4U-bFfQZEgQoUn2amDGWh64216j2UF5vE_UaYvWas72FPIeubDQvvHSnpzrOO2LJzDBa3Al7SZqQKBFZ0ng.jpg?r=e17",
            "title_type": "movie",
            "netflix_id": 81030198,
            "synopsis": "A financial analyst succumbs to a love triangle with a hard-drinking architect and a promiscuous investment bro, who soon becomes her boss.",
            "rating": "0",
            "year": "2011",
            "runtime": "6898",
            "imdb_id": "tt1776143",
            "poster": "https://m.media-amazon.com/images/M/MV5BMjE5MTQwNzM1MV5BMl5BanBnXkFtZTgwNzgyNTA2MDE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-12-01"
        },
        {
            "title": "Don&#39;t Go Breaking My Heart 2",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABShjJSYo6cKuZJ07lNCCgC-B5pl38f58_WIYmMm-81Rkls8JsLRLjI8h0ZCRK42UkIy1EDh2SXkCjnqM9_kv7MoZ8w.jpg?r=47b",
            "title_type": "movie",
            "netflix_id": 80017265,
            "synopsis": "Zixin is about to marry Qihong, but her gallivanting ex returns to wreak havoc as mistaken identities and love triangles stir up the lovers&#39; paradise.",
            "rating": "0",
            "year": "2014",
            "runtime": "6780",
            "imdb_id": "tt3121474",
            "poster": "https://m.media-amazon.com/images/M/MV5BOGIyNDcxYmUtYzdkYi00ZTJjLTlmY2MtMzcwNjRkNzI4YjNmXkEyXkFqcGdeQXVyMjg0MTI5NzQ@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-11-30"
        },
        {
            "title": "El Camino: A Breaking Bad Movie",
            "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABaPN4zj3X7-g8_1fJ3CXFqHbbM2n2OzUcTl6tehr-sMHIc5QUBjKRNUTtpres0AUjCKOKMR2cDSqYz9-fylwMAzZfbMa3ai505cetFHYERvR2UMduAKUYzgZU0M.jpg?r=d66",
            "title_type": "movie",
            "netflix_id": 81078819,
            "synopsis": "Fugitive Jesse Pinkman attempts to outrun his past. Written and directed by &#39;Breaking Bad&#39; creator Vince Gilligan, starring Aaron Paul.",
            "rating": "0",
            "year": "2019",
            "runtime": "7362",
            "imdb_id": "tt9243946",
            "poster": "https://m.media-amazon.com/images/M/MV5BNjk4MzVlM2UtZGM0ZC00M2M1LThkMWEtZjUyN2U2ZTc0NmM5XkEyXkFqcGdeQXVyOTAzMTc2MjA@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-10-11"
        },
        {
            "title": "Erin Brockovich",
            "img": "https://occ-0-1926-41.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABWvHDjmxzMpTovMioQnmZAR6POHH5p2OVUk4YCYrdngwBC6lB06B6qNFhkaUUviUJ6jqvRJhqOPYN7URR_61wKiEIA.jpg?r=028",
            "title_type": "movie",
            "netflix_id": 60000165,
            "synopsis": "Julia Roberts earned an Oscar in this emotional drama for her portrayal of a twice-divorced mother who sees an injustice and takes on the bad guys.",
            "rating": "3.775849",
            "year": "2000",
            "runtime": "7870",
            "imdb_id": "tt0195685",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BYTA1NWRkNTktNDMxNS00NjE4LWEzMDAtNzA3YzlhYzRhNDA4L2ltYWdlXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Es por tu bien",
            "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXe2J1wfr_RJLbi-kOBSf4aQRf1z4G-ThfVmFAoScmcAOnIx-Tj-emsirYoVvPEgN8ryqmhDhT65knuiOIUGaxrLMg.jpg?r=370",
            "title_type": "movie",
            "netflix_id": 80202503,
            "synopsis": "Three brothers-in-law join forces to secretly drive away their daughters&#39; undesirable boyfriends: anarchist Álex, bad-boy Dani and playboy Ernesto.",
            "rating": "0",
            "year": "2017",
            "runtime": "5565",
            "imdb_id": "tt5790492",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNjljMDhkOGEtZTQ2Ny00ZTc2LWFmNjgtNWVjMmRiNjBkM2EwL2ltYWdlL2ltYWdlXkEyXkFqcGdeQXVyMjEyOTkzNTQ@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-10-01"
        },
        {
            "title": "Fantozzi subisce ancora",
            "img": "https://occ-0-784-778.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfRwETUexSU_L2YK6WaIBl5ycKucrrtLIyOvbPQXYsc78tLHpsFXuVeqyPp2p3XGZ7BtTuZnS0BMAt_x9cJyOEMw5g.jpg?r=033",
            "title_type": "movie",
            "netflix_id": 81233995,
            "synopsis": "Plagued with bad luck, Fantozzi learns of his daughter&#39;s pregnancy, sparking a series of unfortunate events including an unexpected operation.",
            "rating": "0",
            "year": "1983",
            "runtime": "5011",
            "imdb_id": "tt0085524",
            "poster": "https://m.media-amazon.com/images/M/MV5BODJkMGZhOTItZjdmNC00YmUzLWEwYWQtMDVlYzFkYjM0MTM5XkEyXkFqcGdeQXVyMzIzNDU1NTY@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-01-01"
        },
        {
            "title": "Fat Choi Spirit",
            "img": "https://occ-0-64-325.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABYCb59lV3fTxb7FSVWJh6sIPL8d0Ph4LHRg1hMV10liJrCGgtKXKCMr1-TtnciqDritT2DNspLPjai9fUtX97_xWag.jpg?r=bc8",
            "title_type": "movie",
            "netflix_id": 81058736,
            "synopsis": "A mah-jongg master tries to dodge a streak of bad luck while winning over his ex-girlfriend, estranged family and a local gang.",
            "rating": "0",
            "year": "2002",
            "runtime": "5810",
            "imdb_id": "tt0307034",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZDNkZGYzMTItOWFiMS00ZGY0LThjZDUtN2Y3NGQxZjYwZjBiXkEyXkFqcGdeQXVyNDEzMDUwNjY@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-01-31"
        },
        {
            "title": "Fitoor",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABU6Eo_HaOaFeaD0L7je9KpAht190ysoeRKHABb6_z85OkHj12tEem7NseFCJCdm5HYPeIYmK22L6IKkXh15wKF3GHw.jpg?r=6e1",
            "title_type": "movie",
            "netflix_id": 80099083,
            "synopsis": "A young artist falls for an aristocratic young woman whose bitter mother has trained her in the art of breaking hearts.",
            "rating": "0",
            "year": "2016",
            "runtime": "7438",
            "imdb_id": "tt4399594",
            "poster": "https://m.media-amazon.com/images/M/MV5BOWVhMjhjZWUtYjNlYS00ZGE3LTg2NTMtM2RhNTE5NGM3YzZmXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-08-02"
        },
        {
            "title": "Focus",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQGPHICjv2bkjZvjvycnatEdhMVYixbQoWS0OJ0rkN_jlTaT17G_v0vLule_RKemAN6iO1YbGMifthG6QSvwEZPF9w.jpg?r=884",
            "title_type": "movie",
            "netflix_id": 80015343,
            "synopsis": "Three years after breaking off a romance with his protégé, expert con man Nicky Spurgeon finds her on the other side of his elaborate new scam.",
            "rating": "3.4181085",
            "year": "2015",
            "runtime": "6279",
            "imdb_id": "tt2381941",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTUwODg2OTA4OF5BMl5BanBnXkFtZTgwOTE5MTE4MzE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-01-13"
        },
        {
            "title": "Francesco De Carlo: Cose di Questo Mondo",
            "img": "http://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABeXjp0BGRf4JfXB_cdwn_beMB4zHnQvnfHue92jkC631etY9F_1-RO3SHhuyxep88mbiKdng4TL4C10RDc-AeQYsE6Ti4bCmKAX_nR_RmPHlJS6uP2kID9d6p74.jpg?r=9bf",
            "title_type": "movie",
            "netflix_id": 81041272,
            "synopsis": "Taking the stage in Milan, Francesco De Carlo opens up about his bad habits, religion, politics and what he&#39;s learned from traveling the world.",
            "rating": "0",
            "year": "2019",
            "runtime": "3678",
            "imdb_id": "tt10087952",
            "poster": "",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-04-12"
        },
        {
            "title": "Girl on the Third Floor",
            "img": "https://occ-0-1091-300.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABb2NZicsgerrSi5-nxlWu0ghYIfCm0-xxLgJvjkhVhkeeV1A2HTu8s_PrgiwK530eHvFtY78w7ehI2VPmhlcHkvrzg.jpg?r=96d",
            "title_type": "movie",
            "netflix_id": 81082119,
            "synopsis": "A husband with a bad track record tries to start anew by renovating a rundown Victorian for his family, only to find he&#39;s tackled a house out of hell.",
            "rating": "0",
            "year": "2019",
            "runtime": "5520",
            "imdb_id": "tt9026184",
            "poster": "https://m.media-amazon.com/images/M/MV5BNmM3ZTJmMmYtYjhlOS00MzkzLWJkYWQtN2E0NjZlZGM3NDc5XkEyXkFqcGdeQXVyMjM4NTM5NDY@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-02-22"
        },
        {
            "title": "Guardianes de Oz",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfi9_EUXHt4z2aG3eiarBi6OL3dprbw6GHYrfzDSVf6WDQlBHWxvrKiJJQNf423FSSeXd-UW-ggYg8dQwcLQSkOIkw.jpg?r=456",
            "title_type": "movie",
            "netflix_id": 80065581,
            "synopsis": "The flying monkeys of the Oz stories weren&#39;t all bad. Ozzy and his pals rebel against the Wicked Witch of the West and try to make Oz a better place.",
            "rating": "3.064516",
            "year": "2015",
            "runtime": "5149",
            "imdb_id": "tt3633118",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BOTkxMTQwNGMtOTRjZS00NTU5LTk1NGMtYjk1OTY1OGJmNjM5XkEyXkFqcGdeQXVyMjgzNjA3Mw@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-10-20"
        },
        {
            "title": "Gully",
            "img": "https://occ-0-2903-778.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdBopf_MWHoKiZgCkEjB5IM5XE4JXn8akDTMdNEXYACnARqVDOXUJ0HJqLLZkC7_1FAK5nlITrF0uwF9hFA8OEdLoA.jpg?r=34b",
            "title_type": "movie",
            "netflix_id": 81092067,
            "synopsis": "After surviving traumatic childhoods, three disillusioned teens reach a breaking point and go on a nihilistic rampage through modern-day Los Angeles.",
            "rating": "0",
            "year": "2021",
            "runtime": "5075",
            "imdb_id": "tt5013984",
            "poster": "https://m.media-amazon.com/images/M/MV5BZTMwZWMyODctM2E3ZS00Yzk1LWFjMWQtN2I4YmJkNGU0M2Y0XkEyXkFqcGdeQXVyMTAyMjQ3NzQ1._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-12-17"
        },
        {
            "title": "Heartbreaker",
            "img": "https://occ-0-768-769.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdk1CuBjFXe5QzD4r5EtWdBtR8mYBhAuQuwA3zL3QrZ9tIpPEMKgIvlzkm76641_CU7WEKGmQiV44RBEU8CUAfAU2A.jpg?r=fe1",
            "title_type": "movie",
            "netflix_id": 70136041,
            "synopsis": "Alex earns money by breaking up relationships, but when he falls for a client&#39;s daughter, he must decide whether to ruin her wedding to Mr. Right.",
            "rating": "3.599708",
            "year": "2010",
            "runtime": "6290",
            "imdb_id": "tt1465487",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjI0NjU5ODYwM15BMl5BanBnXkFtZTcwOTk5NDI3Mw@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "HOW TO BUILD A GIRL",
            "img": "https://occ-0-1081-999.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABe_fxMSBM1E-sSoszr12SmkI-498sqBWrEyhkchdn4UklQVjdoPS_Hj-NhvgbePvwlDSzMTcrIE0kgiy-zTEU_EaGg.jpg?r=35a",
            "title_type": "movie",
            "netflix_id": 81041267,
            "synopsis": "When nerdy Johanna moves to London, things get out of hand when she reinvents herself as a bad-mouthed music critic to save her poverty-stricken family.",
            "rating": "0",
            "year": "2020",
            "runtime": "6239",
            "imdb_id": "tt4193072",
            "poster": "https://m.media-amazon.com/images/M/MV5BZGUyN2ZlMjYtZTk2Yy00MWZiLWIyMDktMzFlMmEzOWVlMGNiXkEyXkFqcGdeQXVyMTE1MzI2NzIz._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-03-04"
        },
        {
            "title": "If I Were a Boy",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABcIGBvMNlIdt9swS2I_OEtTI1cm0KliW4yZS37u6TOCwcRs19Ry4xLvsKALD2-fU4pCyQrRSRlfCKZUu_hiqnl9Wng.jpg?r=3da",
            "title_type": "movie",
            "netflix_id": 80996708,
            "synopsis": "Burned by a bad marriage, a woman is fed up with men. But life gets more complicated after she wakes up one morning with male anatomy.",
            "rating": "0",
            "year": "2017",
            "runtime": "5896",
            "imdb_id": "tt5598172",
            "poster": "https://m.media-amazon.com/images/M/MV5BYTUzYjM3MDEtZDMxMy00ZjdlLWI0YzAtZDI0MjBhYTY0ZDEyXkEyXkFqcGdeQXVyNjMxMTczNjI@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-04-12"
        },
        {
            "title": "Ingo Appelt - Männer muss man schlagen",
            "img": "http://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABSVEQ677n5vm-gV8UqRYhqzrD2OPLtMz0alj7KOjd4V9ZQsV9NNeWuq9UmO9Zk7CfiiWe-pOEfwZY9vX3b3-ZvS9dA.jpg?r=4c6",
            "title_type": "movie",
            "netflix_id": 80095721,
            "synopsis": "Sharp-tongued comedian Ingo Appelt pulls no punches as he pokes fun at men, taking them to task for all sorts of bad behavior.",
            "rating": "3",
            "year": "2008",
            "runtime": "6560",
            "imdb_id": "notfound",
            "poster": "",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-03-01"
        },
        {
            "title": "Jack Irish: Bad Debts",
            "img": "https://occ-0-753-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRLAqZUz7Lj53aM1KqEzlHafoOFe-xgS4LH1fXD-4p4S5zFf-Xu-kPaiYmSuw8hbWdEFQr52goxOtK47yWBFaqQ0dA.jpg?r=9f4",
            "title_type": "movie",
            "netflix_id": 80028142,
            "synopsis": "Former lawyer Jack Irish probes the suspicious death of an old client who was killed shortly after reaching out to him for help.",
            "rating": "3.9833333",
            "year": "2012",
            "runtime": "5982",
            "imdb_id": "tt2087820",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTczMjc0NDI2NF5BMl5BanBnXkFtZTgwMTQ2NjAxMzE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Jackass Presents: Bad Grandpa",
            "img": "https://occ-0-753-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABR8dDHuL0IJqkFva9ujabsJ7DexchZe1mNXPjX6ufaiC7WTSIoH4Jc8RiujTMTpr2ASflXCf_zTmqU3l7IDzrPPT8w.jpg?r=d46",
            "title_type": "movie",
            "netflix_id": 70286879,
            "synopsis": "In-character encounters with real folks provide plenty of comic fodder in this franchise featuring Johnny Knoxville in lecherous-gramps disguise.",
            "rating": "3.6926882",
            "year": "2013",
            "runtime": "5503",
            "imdb_id": "tt3063516",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg4NjIwMTI5OV5BMl5BanBnXkFtZTgwNjU1MTMyMDE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Jerry Seinfeld: 23 Hours To Kill",
            "img": "http://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABZYpYoSVJlOYu9XFj35bwyHs8YmqcO5-JVPHjLzIJMd2YitFVBQDDAPS1GAAWZm3BOggwRC4ZSa3ar8fAODkXjO6iXRZUMoJVek5DzSEDiEeBeF6PEG_psK0M38.jpg?r=490",
            "title_type": "movie",
            "netflix_id": 80170847,
            "synopsis": "Jerry Seinfeld takes the stage in New York and tackles talking vs. texting, bad buffets vs. so-called &#39;great&#39; restaurants and the magic of Pop Tarts.",
            "rating": "0",
            "year": "2020",
            "runtime": "3636",
            "imdb_id": "tt12117854",
            "poster": "https://m.media-amazon.com/images/M/MV5BZTQ0ZWFlY2QtZmVmOC00OWZkLWI2NDMtNzliOWU4ZTc5NjJmXkEyXkFqcGdeQXVyNzg5MzIyOA@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-05-05"
        },
        {
            "title": "Jim Jefferies: Intolerant",
            "img": "https://occ-0-1348-2773.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQiDL2wJUYJjAQt5VD2atmyP3mPgDqNV91VmZBmqVz4svU5vfgKmiFZpsNnzO1xvuK183SqOCaZHoUfu-tp_KIVUHN7TjDH5NyjME0YeuVr3WZRswswhhx66DH4.jpg?r=56e",
            "title_type": "movie",
            "netflix_id": 81121954,
            "synopsis": "Between scenes from an excruciating date, Jim Jefferies digs into generational differences, his own bad habits and the shifting boundaries in comedy.",
            "rating": "0",
            "year": "2020",
            "runtime": "3991",
            "imdb_id": "tt12588160",
            "poster": "https://m.media-amazon.com/images/M/MV5BZGI1YTYwODgtMWE0OC00ZWY2LWJhZTgtZDJhMDIyNjU0Y2IzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-07-07"
        },
        {
            "title": "Jinxed",
            "img": "https://occ-0-2219-2218.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABd8Q-aAJc76oZZ6W4NhhZZDxrs902rlwUdX0B08aoLyAmzZMX373WTeBFblLbZ1ZB8KlTTtLQbWHkcVYiYc_Rf7NmA.jpg?r=0b3",
            "title_type": "movie",
            "netflix_id": 81214187,
            "synopsis": "After a century-old curse of bad luck, a determined teen embarks on a journey to break her family’s generational misfortune.",
            "rating": "0",
            "year": "2013",
            "runtime": "4150",
            "imdb_id": "tt2934844",
            "poster": "https://m.media-amazon.com/images/M/MV5BMTY4NjA0OTA5MF5BMl5BanBnXkFtZTgwOTIwMTY3MDE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-11-02"
        },
        {
            "title": "Joking Jazz 4G",
            "img": "https://occ-0-64-325.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABVr1HhK75P-WiFegC_IuQW5QnYKmyIW3W-8PvA41sYmeghBKfpGUT8_cuictbMatw49yslqJ2MwFjfyI2GpzG1dF6Q.jpg?r=1dd",
            "title_type": "movie",
            "netflix_id": 81072905,
            "synopsis": "A tatted bad boy-turned-newly ordained monk is forced to use tactics from his checkered past on an unexpected Buddhist mission in Bangkok.",
            "rating": "0",
            "year": "2016",
            "runtime": "6559",
            "imdb_id": "tt6449704",
            "poster": "https://m.media-amazon.com/images/M/MV5BOTZhZDM4YmYtZWRjMy00YWQwLWJmZjQtMjM0OTVmMTc5ZDM0XkEyXkFqcGdeQXVyNTA2NjYxMjI@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-04-01"
        },
        {
            "title": "Jonas",
            "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfWiy5Y-pCI6Hiv2APR9NCCHwfIgAftkufa6epgW96-Qv2eS6iiOeIylrgszOyUMZz_rcYvgWHICfT4TpXb-LKUD1w.jpg?r=fb3",
            "title_type": "movie",
            "netflix_id": 80119235,
            "synopsis": "During Carnival, two teens from different classes meet years after being kept apart. Bad decisions lead the boy to hide with the girl inside a float.",
            "rating": "3.125",
            "year": "2015",
            "runtime": "5801",
            "imdb_id": "tt1044418",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTU2MTQ4MjExM15BMl5BanBnXkFtZTcwODM0MTM1Mg@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-02-26"
        },
        {
            "title": "Just My Luck",
            "img": "https://occ-0-753-1360.1.nflxso.net/dnm/api/v6/XsrytRUxks8BtTRf9HNlZkW2tvY/AAAABaG1u65fp5g0ao_OPqbULSlwxGr1AFBswTPSSkD6dMCUQ6o1lBZPS17_wWMgdfyFhK5A4yc4RrQ-nOO7VfYorkU07Vs6hms.jpg?r=3c8",
            "title_type": "movie",
            "netflix_id": 70042692,
            "synopsis": "After a chance meeting with a rock group&#39;s jinxed manager, independent New Yorker Ashley discovers that she&#39;s caught his bad luck like a disease.",
            "rating": "3.1290524",
            "year": "2006",
            "runtime": "6130",
            "imdb_id": "tt0397078",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTczMDg2ODUyMl5BMl5BanBnXkFtZTcwMjcyMzgzMQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Justice, My Foot!",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABRN4XZEcpb6oFoCfYLNl-7Qw1E0efexv8o-BXNsezAD75xaT0Pjz1UbRbrByXp2C9xnpmOEHnsOcqts8MT-gSPuBew.jpg?r=486",
            "title_type": "movie",
            "netflix_id": 70033611,
            "synopsis": "Slick lawyer Sung fears he&#39;s been cursed with bad karma and considers giving up his practice -- until he&#39;s approached by a widow accused of murder.",
            "rating": "3",
            "year": "1992",
            "runtime": "5720",
            "imdb_id": "tt0105385",
            "poster": "http://ia.media-imdb.com/images/M/MV5BMTg3NzIxMTE2N15BMl5BanBnXkFtZTcwNTU3ODUxMQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-08-22"
        },
        {
            "title": "Kaminey",
            "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABd2w6IIqiDRoiL-ueSSx0za63YIzf6X2OxILRdDTMLsELohAdYvxMIXE0BnVQsayfCnIItA_VuOrcRJ44cc3cFr1vg.jpg?r=732",
            "title_type": "movie",
            "netflix_id": 70117268,
            "synopsis": "A young man pursues his dreams of wealth by breaking the law, while his twin brother tries to better his life through hard work and honesty.",
            "rating": "0",
            "year": "2009",
            "runtime": "7707",
            "imdb_id": "tt1274295",
            "poster": "https://m.media-amazon.com/images/M/MV5BMTM2MTQ4NTY1Nl5BMl5BanBnXkFtZTcwMDI3NTU2Mg@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-10-01"
        },
        {
            "title": "Kyaa Kool Hai Hum",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdo8Rr9Cl-4-pJV9AvnFYNeHtoBvYrzxT0W4VJl3K1FO8OIS5Brtz6dzbaBszC6UrbEhnbmbEB6tLvQXh0kyXf71kA.jpg?r=a82",
            "title_type": "movie",
            "netflix_id": 70035357,
            "synopsis": "Longtime friends Rahul and Karan head to Mumbai intent on making their dreams come true, but both men are suddenly saddled with bad luck.",
            "rating": "2.8558366",
            "year": "2005",
            "runtime": "9899",
            "imdb_id": "tt0456500",
            "poster": "http://ia.media-imdb.com/images/M/MV5BMjA4MzM3ODE5MF5BMl5BanBnXkFtZTgwMzI1MDA2MDE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-01-06"
        },
        {
            "title": "LEGO: Marvel Super Heroes: Maximum Overload",
            "img": "https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABc-0dYCQZ_oTPl1QWa6v1XjCaNwFc4CCMkZ64xLzCIwoQ0-p6qjCocUhFi1PigBI3nXqbBHSbj9b40k_3ROEgBBt3w.jpg?r=483",
            "title_type": "movie",
            "netflix_id": 70295415,
            "synopsis": "Villainous Loki is amassing an army to conquer Earth! His antics are keeping Spider-Man and S.H.I.E.L.D. busy as they tackle a host of bad guys.",
            "rating": "3.6946542",
            "year": "2013",
            "runtime": "1327",
            "imdb_id": "tt3322904",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNmFiZTVmOTktOTk2OS00NGMyLWE0NWItMWFlYmQ5Yjg2ODhjXkEyXkFqcGdeQXVyNjQyNzU5NzU@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Living in Bondage: Breaking Free",
            "img": "https://occ-0-3750-185.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABSQeHP3110ifP9WBDCJXRmAnwAcrNhJDxvBpzlLHdlrzsEGxrhuOy_I4F4QUI574xu47hISs4i5GeqAL9gWZ2D9nVA.jpg?r=736",
            "title_type": "movie",
            "netflix_id": 81270668,
            "synopsis": "Mentored by an enigmatic tycoon, an ambitious young man faces a crisis when his rise in power draws him deep into the occult.",
            "rating": "0",
            "year": "2019",
            "runtime": "8941",
            "imdb_id": "tt12539758",
            "poster": "https://m.media-amazon.com/images/M/MV5BMTdmNzUyMmMtN2U1Mi00Nzk1LWJlNTgtYWRjN2ViN2U0YWFlXkEyXkFqcGdeQXVyMzQ3Nzc1MTA@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-05-22"
        },
        {
            "title": "Lommbock",
            "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXitS0kWW_L8Y2CL1bUnUSc30W1_trLPuGBoWWCjhnXHCXzUJwatuog8pfoB1OR2Agwph7tTXNT9iPE6A7cx_LMlDA.jpg?r=6a4",
            "title_type": "movie",
            "netflix_id": 80191219,
            "synopsis": "After finding love in drug-free Dubai, Stefan returns to Germany to grab documents for his wedding. But old buddy Kai&#39;s bad habits complicate things.",
            "rating": "0",
            "year": "2017",
            "runtime": "6371",
            "imdb_id": "tt5075584",
            "poster": "https://m.media-amazon.com/images/M/MV5BNjU1NWYwZTAtYTQzYS00MzNmLTgxNGYtZDMwYzA3ZjE0YTYzXkEyXkFqcGdeQXVyMjQ3NzUxOTM@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2018-11-09"
        },
        {
            "title": "Luck-Key",
            "img": "https://occ-0-1007-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAAAapOps79fvOHCCV5y4nN1fiXUgznrW432YhMbLx0vvjZ7VegxwwM8hG9OKbRh1tDfOgydmrqFGn1ICsJdQM-QwxSjw.jpg?r=710",
            "title_type": "movie",
            "netflix_id": 80149102,
            "synopsis": "A poor, no-name actor decides to switch locker keys -- and lives -- with a wealthy hit man who loses his memory from a bad fall in a public bathhouse.",
            "rating": "0",
            "year": "2016",
            "runtime": "6758",
            "imdb_id": "tt6175078",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzE5NDM4ZTYtZTM1YS00ZTQ5LWE4MjUtOTc0OGVmZmIwMDEwXkEyXkFqcGdeQXVyNjk0MzU1NTA@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-09-30"
        },
        {
            "title": "Middle School: The Worst Years of My Life",
            "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABaXDPTtsmJ0talJgfBeHqbleZcpOFL84LdC_P_YtMuEHfNJXA39jv0YcAyAa9EUJsfeTmpTmzcSahZ9NowHOU1ZWWEuYUSNEM9JUR0sNtF8qZ9F1_xdUqVqFc14.jpg?r=17a",
            "title_type": "movie",
            "netflix_id": 80105067,
            "synopsis": "At Hills Village Middle School, budding cartoonist Rafe and best pal Leo challenge their uptight principal by breaking every rule in his handbook.",
            "rating": "3.1966054",
            "year": "2016",
            "runtime": "5529",
            "imdb_id": "tt4981636",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNjQzMTczNjI0Ml5BMl5BanBnXkFtZTgwODY5MTY5OTE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-02-10"
        },
        {
            "title": "Money",
            "img": "https://occ-0-1007-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABSSNdBaAGjHJ8x8GbMZW39baeUYwTk9YldDKFV7LoHI5_gQ7lyHDWmO7edm8lusfIx3O67C5AhSkQS4pP3KrWgvgRSZWMiW1NBcQ8sr2sPiY7E2uWaxjyvXwDhHBk6si7HE1mY7YJkK3aNwOkD6f0aDuBw.jpg?r=6b3",
            "title_type": "movie",
            "netflix_id": 81105952,
            "synopsis": "A fledgling stockbroker with dreams of getting rich despite being bad at his job accepts a shady proposal, catching the eye of a dogged investigator.",
            "rating": "0",
            "year": "2019",
            "runtime": "6912",
            "imdb_id": "tt4715356",
            "poster": "https://m.media-amazon.com/images/M/MV5BZDYzY2MwYmEtMmU4MC00Y2M4LWE3ODMtMjJlZTUwZWU5MzNjXkEyXkFqcGdeQXVyMTc2NjA0MzE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-08-02"
        },
        {
            "title": "Mr. Right",
            "img": "http://occ-0-1091-300.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABXQeWYmaJHP6SOeQc-q0mla3eAreDRraPO_Vracy59jhCZ2VCjtvKHJc7fpuJ9AKNd5TfwWt-B7I8hEfDGH_uUfFmg.jpg?r=0e5",
            "title_type": "movie",
            "netflix_id": 80081154,
            "synopsis": "Fresh off a bad relationship, thrill-seeking Martha finds romance and danger with Francis, a hit man who&#39;s decided to turn the tables on his clients.",
            "rating": "3.4696429",
            "year": "2015",
            "runtime": "5737",
            "imdb_id": "tt2091935",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BOTcxNjUyOTMwOV5BMl5BanBnXkFtZTgwMzUxMDk4NzE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-05-02"
        },
        {
            "title": "Nitro Rush",
            "img": "https://occ-0-724-2433.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQz68mY7DUqpj1lwqw19ap6z_xy74lQUIsglGdlIX1sNFDvbPTm8h1BrZi0B_wmhEURY__KxGzGev1D13S8zvMKN0Q.jpg?r=17c",
            "title_type": "movie",
            "netflix_id": 81478300,
            "synopsis": "In this \"Nitro\" sequel, former drag racer Max risks everything by breaking out of prison to rescue his son from the clutches of a criminal organization.",
            "rating": "0",
            "year": "2016",
            "runtime": "5791",
            "imdb_id": "tt4579914",
            "poster": "https://m.media-amazon.com/images/M/MV5BMTIzOWI5ZTgtOWUxZC00MDA4LWE0MmItMjc4ZmEyYzYxOWViXkEyXkFqcGdeQXVyNTA1NDY3NzY@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-11-02"
        },
        {
            "title": "No Country for Old Men",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABX9e9Jtk8s5qFutTnarSlnlWvl2ZwnvbClQWN4IHGn66WC_CZg8RzzlIrcJL0KLVp9FRgp2CUfJaWjDdNXXLcjyYcQ.jpg?r=9df",
            "title_type": "movie",
            "netflix_id": 70071613,
            "synopsis": "While hunting, Llewelyn Moss stumbles upon a drug deal gone bad and takes off with $2 million in cash, but a psychotic hit man is hot on his trail.",
            "rating": "3.7557018",
            "year": "2007",
            "runtime": "7335",
            "imdb_id": "tt0477348",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjA5Njk3MjM4OV5BMl5BanBnXkFtZTcwMTc5MTE1MQ@@._V1_SX300.jpg",
            "top250": 156,
            "top250tv": 0,
            "title_date": "2015-04-14"
        },
        {
            "title": "Nobody&#39;s Daughter Haewon",
            "img": "https://occ-0-1361-988.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTweRyYnK692MNX8S-yHVMQrg5sv4ut_mzoyUnHvpBB1XGC7nk6Vi_q7FT5Ov4zNNoMNsrQqlMr09zkSyMq3aEYnEw.jpg?r=44b",
            "title_type": "movie",
            "netflix_id": 70271068,
            "synopsis": "Haewon has reached the breaking point in her relationship with her married professor, who refuses to acknowledge that they&#39;re finished.",
            "rating": "0",
            "year": "2013",
            "runtime": "5408",
            "imdb_id": "tt1068774",
            "poster": "https://m.media-amazon.com/images/M/MV5BMTcxMTY2OTU0Ml5BMl5BanBnXkFtZTcwMTc4MzEwMg@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-12-28"
        },
        {
            "title": "Other People",
            "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTdCVa64IEcrUWlmNxHoLNNyrdBynETg5S4pRqY-0NG7Eq1Qepe01ZqXd0UxZfndnYCjUvFlkeqSRW302ce-SM-EFA.jpg?r=f69",
            "title_type": "movie",
            "netflix_id": 80098288,
            "synopsis": "After a bad breakup, a struggling New York comedy writer tries to don a brave face and care for his dying mother in Sacramento.",
            "rating": "3.127016",
            "year": "2016",
            "runtime": "5828",
            "imdb_id": "tt4158876",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTk2NzUzNTgyNl5BMl5BanBnXkFtZTgwNjkzODM2OTE@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-12-07"
        },
        {
            "title": "Our Times",
            "img": "https://occ-0-1007-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABQkK3aY9rkrGSBPbLQKfM31dyQshdLpeLe03HhvXzrpnp9y0iIdWJPS6oSZuWy1ZcBPSKcCiwRD7f-bs51cjBvFtBg.jpg?r=97b",
            "title_type": "movie",
            "netflix_id": 80091937,
            "synopsis": "The high school bad boy and a smart but awkward girl form an unlikely alliance to help each other land their dream dates.",
            "rating": "0",
            "year": "2015",
            "runtime": "8043",
            "imdb_id": "tt4967094",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BNjYzOTVkMjQtZTY1My00MzJlLWE5NmQtZWE5NGY4NjZkMmQ0XkEyXkFqcGdeQXVyNjQ1OTAwMzc@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2017-06-09"
        },
        {
            "title": "Paradise Hills",
            "img": "https://occ-0-2717-360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfGE7TADc_aC2zDuPmDGT3w_3SWNfGWLVs47HIx-m3dWLJKWx_GuAybBmlKCM__Q1S_dzTz7ldSkPAr0NkiPpBtrcw.jpg?r=549",
            "title_type": "movie",
            "netflix_id": 80223140,
            "synopsis": "Uma wakes up in a lush tropical facility designed to turn willful girls into perfect ladies. That’s bad enough, but its real purpose is even worse.",
            "rating": "0",
            "year": "2019",
            "runtime": "5670",
            "imdb_id": "tt6127004",
            "poster": "https://m.media-amazon.com/images/M/MV5BMmQwY2QwZjgtNDgxNy00YTM2LWEzNjQtMjI0YjQ5ZGM0OGY1XkEyXkFqcGdeQXVyMzQwMTY2Nzk@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2020-02-28"
        },
        {
            "title": "Paradox",
            "img": "https://occ-0-1007-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABdjlMkUCknKRp8HColQWa15N1H1WbSdw_ch1awc6G_gikBrJl93bJLMTmjYJ5mn9oTu4XbJ4RFtevVuxh-h654x7tA.jpg?r=dac",
            "title_type": "movie",
            "netflix_id": 80994225,
            "synopsis": "Bone-breaking violence erupts as a Hong Kong cop faces corrupt politicians and organ traffickers while looking for his abducted daughter in Thailand.",
            "rating": "0",
            "year": "2017",
            "runtime": "5988",
            "imdb_id": "tt7245176",
            "poster": "https://m.media-amazon.com/images/M/MV5BMTEzYzczMTctNTJhMy00YTdiLWJkZTAtNGM0YzYyMjMyY2VmXkEyXkFqcGdeQXVyNjgwNTk4Mg@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2019-10-01"
        },
        {
            "title": "Piece of Cake",
            "img": "https://occ-0-1007-1360.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABTGY2ObowzUF8uLXTbQFQ4c8LFUgyNEMyEAj_MrjDeqoZ6iwM0EOX5KwvBcz-CE1fediTRfypwpfB3eGZjOUtY60Kg.jpg?r=0f6",
            "title_type": "movie",
            "netflix_id": 80139913,
            "synopsis": "Shino Umemiya moves to a new location to get away from a bad relationship and develops a crush on her neighbor Kyoshiro, who&#39;s also her new manager.",
            "rating": "3.060606",
            "year": "2015",
            "runtime": "7294",
            "imdb_id": "tt4061360",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BZjMwOTE0MjUtZGExMi00YWZjLTgwYjYtZDczMWE5NGZmMmZhXkEyXkFqcGdeQXVyMjAwMzU2MDY@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2016-11-09"
        },
        {
            "title": "Punk in London",
            "img": "https://occ-0-56-55.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABep2IwwNL3_uf_kWFL59GBTtlmzVfaznKI8vqM3yBPNMepR81JYE8kSxtd3gOBTABayKEOhmhwC8NL7QCCeGEgp1tw.jpg?r=c0d",
            "title_type": "movie",
            "netflix_id": 70118168,
            "synopsis": "Relive the good, the bad and the anarchic of Britain&#39;s punk scene with this raw documentary featuring performances by X-Ray Spex, the Clash and more.",
            "rating": "0",
            "year": "1977",
            "runtime": "5375",
            "imdb_id": "tt0079763",
            "poster": "https://m.media-amazon.com/images/M/MV5BMTY4MzY2ODc0N15BMl5BanBnXkFtZTcwNzE5NDUzMQ@@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2021-10-17"
        },
        {
            "title": "Rambo: First Blood",
            "img": "https://occ-0-2773-2774.1.nflxso.net/dnm/api/v6/evlCitJPPCVCry0BZlEFb5-QjKc/AAAABfIQPvQi5lNerh-PLycLh8mC_Cfqz5nDhg6U0fXIkc-dHiG_ZNyMVjDyxsye26_0r9GE0pVSA-RVx4P-Jfn7gEXhiw.jpg?r=598",
            "title_type": "movie",
            "netflix_id": 70017963,
            "synopsis": "Targeted by a small-town sheriff, former Green Beret and Vietnam vet John Rambo reaches his breaking point and launches a guerilla response.",
            "rating": "3.7422886",
            "year": "1982",
            "runtime": "5600",
            "imdb_id": "tt0083944",
            "poster": "https://images-na.ssl-images-amazon.com/images/M/MV5BODBmOWU2YWMtZGUzZi00YzRhLWJjNDAtYTUwNWVkNDcyZmU5XkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg",
            "top250": 0,
            "top250tv": 0,
            "title_date": "2015-04-14"
        }
    ]
}